version: '3.8'
services:
  consul:
    image: hashicorp/consul:1.20
    ports:
      - "8500:8500" # Consul HTTP API
      - "8600:8600/udp" # Consul DNS
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"dc1","server":true}
    networks:
      - app-network
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.58
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - app-network
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      - repair-service
      - consul
      - jaeger
    ports:
      - "8081:8081"
    environment:
      - CONSUL_ADDRESS=consul:8500
      - SERVICE_NAME=api-gateway
      - SERVICE_PORT=8081
      - JAEGER_ENDPOINT=http://jaeger:4318/v1/traces
    restart: unless-stopped
    networks:
      - app-network

  repair-service:
    build:
      context: ./repair-service
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - consul
      - jaeger
    ports:
      - "8080:8080"
    environment:
      - CONSUL_ADDRESS=consul:8500
      - SERVICE_NAME=repair-service
      - SERVICE_PORT=8080
      - JAEGER_ENDPOINT=http://jaeger:4318/v1/traces
    restart: unless-stopped
    networks:
      - app-network

  mechanic-service:
    build:
      context: ./mechanic-service
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - consul
      - jaeger
    ports:
      - "8082:8082"
    environment:
      - CONSUL_ADDRESS=consul:8500
      - SERVICE_NAME=mechanic-service
      - SERVICE_PORT=8082
      - JAEGER_ENDPOINT=http://jaeger:4318/v1/traces
      - MONGO_URI=mongodb://admin:admin@mongodb:27017/repairdb?authSource=admin
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=repairdb
    volumes:
      - mongodb_data:/data/db
      - ./init_mechanics.js:/docker-entrypoint-initdb.d/init_mechanics.js:ro
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
