version: '3.8'

services:
  mongodb:
    image: mongo:latest
    pull_policy: never
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    restart: unless-stopped
    command: mongod

volumes:
  mongodb_data:
    driver: local
