# kubectl apply -f k8s/consul-nodeport-service.yaml
# kubectl get svc consul-nodeport -n roadride
apiVersion: v1
kind: Service
metadata:
  name: consul-nodeport
  namespace: roadride
spec:
  type: NodePort
  selector:
    app: consul  # Changed to match pod label
  ports:
    - port: 8500
      targetPort: 8500
      nodePort: 30000
      protocol: TCP
