apiVersion: v1
kind: Service
metadata:
  name: consul-loadbalancer
  namespace: roadride
spec:
  type: LoadBalancer
  selector:
    app: consul  # Adjust selector to match Consul server pods
  ports:
    - port: 8500
      targetPort: 8500
      protocol: TCP
