apiVersion: v1
kind: Service
metadata:
  name: consul-nodeport
  namespace: roadride
spec:
  type: NodePort
  selector:
    app: consul
    component: server  # Add to target only server pods
  ports:
    - port: 8500
      targetPort: 8500
      nodePort: 30000
      protocol: TCP
