# kubectl apply -f k8s/consul-nodeport-service.yaml
# kubectl get svc consul-nodeport -n roadride
apiVersion: v1
kind: Service
metadata:
  name: consul-nodeport
  namespace: roadride
spec:
  type: NodePort
  selector:
    # app: consul  # Adjust selector to match Consul server pods
    app.kubernetes.io/name: consul  # Adjust to match pod labels
  ports:
    - port: 8500
      targetPort: 8500
      nodePort: 30000  # Use a port in the range 30000-32767
      protocol: TCP
