apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-app
  namespace: roadride
  labels:
    app: consul-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-app
  template:
    metadata:
      labels:
        app: consul-app
    spec:
      containers:
        - name: consul-app
          image: fadedreams7/consul-app:2
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8089
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8089
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 3
