apiVersion: v1
kind: Service
metadata:
  name: consul-nodeport
  namespace: roadride
spec:
  type: NodePort
  selector:
    app: consul  # Adjust selector to match Consul server pods
  ports:
    - port: 8500
      targetPort: 8500
      nodePort: 30000  # Use a port in the range 30000-32767
      protocol: TCP
