apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: roadride
spec:
  containers:
  - name: kafka-client
    image: confluentinc/cp-kafka:7.3.0
    command: ["/bin/bash"]
    args: ["-c", "export PATH=$PATH:/usr/bin && sleep infinity"]
    volumeMounts:
    - name: client-config
      mountPath: /tmp/client.properties
      subPath: client.properties
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
  volumes:
  - name: client-config
    configMap:
      name: kafka-client-config
  restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-client-config
  namespace: roadride
data:
  client.properties: |
    bootstrap.servers=kafka.roadride.svc.cluster.local:9092
    security.protocol=SASL_PLAINTEXT
    sasl.mechanism=PLAIN
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="user1" password="vq9zGVCbwz";
