apiVersion: v1
kind: Service
metadata:
  name: kafka-app
  namespace: roadride
spec:
  type: NodePort
  ports:
    - port: 8087
      targetPort: 8087
      nodePort: 30087
      protocol: TCP
      name: http
  selector:
    app: kafka-app
