apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-app
  namespace: roadride
  labels:
    app: kafka-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
      - name: kafka-app
        image: fadedreams7/kafka-app:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8087
          name: http
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8087
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8087
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-app
  namespace: roadride
spec:
  type: NodePort
  ports:
    - port: 8087
      targetPort: 8087
      nodePort: 30087
      protocol: TCP
      name: http
  selector:
    app: kafka-app
