auth:
  clientProtocol: sasl
  interBrokerProtocol: sasl
  sasl:
    mechanism: SCRAM-SHA-256
    # Remove jaas.users since SCRAM credentials are managed via kafka-configs.sh

persistence:
  size: 8Gi

resources:
  requests:
    memory: 512Mi
    cpu: 250m

controller:
  replicaCount: 1
  extraConfig: |
    authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
    super.users=User:user1
    allow.everyone.if.no.acl.found=true

broker:
  replicaCount: 0

zookeeper:
  enabled: false

kraft:
  enabled: true
