service:
  type: NodePort
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
      nodePort: 30044  # Optional: Specify a port (30000-32767 range); Kubernetes assigns one if omitted
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080  # Optional: Specify a port
resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "100m"
    memory: "200Mi"
