logstashConfig:
  logstash.yml: |
    http.host: "0.0.0.0"
    http.port: 9600
logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      json {
        source => "message"
      }
    }
    output {
      if [app] == "api-gateway" {
        elasticsearch {
          hosts => ["http://elasticsearch-master:9200"]
          index => "apigateway-logs-%{+YYYY.MM.dd}"
        }
      }
    }
service:
  type: NodePort
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
      nodePort: 30044
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
