apiVersion: v1
kind: Service
metadata:
  name: mechanic-service
spec:
  type: NodePort
  selector:
    app: mechanic-service
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30086  # choose any free port in 30000-32767 range
