apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mechanic-service-logs
  name: mechanic-service-logs
  namespace: roadride
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
