apiVersion: v1
kind: Service
metadata:
  name: mongo-app
  namespace: roadride
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
  selector:
    app: mongo-app
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo-app
#   namespace: roadride
# spec:
#   ports:
#     - port: 8080
#       targetPort: 8080
#       protocol: TCP
#   selector:
#     app: mongo-app
