apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: repairdb-rs
  namespace: roadride
spec:
  members: 1
  type: ReplicaSet
  version: "8.0.1"
  security:
    authentication:
      modes:
        - SCRAM
  users:
    - name: root
      db: admin
      passwordSecretRef:
        name: mongodb-admin-secret
        key: MONGO_INITDB_ROOT_PASSWORD
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: repairdb-rs-root-scram
  persistent: true  # Enables PVCs (default 8Gi; overridden below)
  statefulSet:  # Customizes StatefulSet for storage
    spec:
      template:
        spec:
          volumeClaimTemplates:
            - metadata:
                name: data-volume
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 2Gi
                storageClassName: standard
