apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: repairdb-rs
  namespace: roadride
spec:
  version: "8.0.1"
  type: ReplicaSet
  members: 1  # Reduced to single member for testing
  security:
    authentication:
      modes:
        - SCRAM
  users:
    - name: root
      db: admin
      passwordSecretRef:
        name: mongodb-admin-secret
        key: MONGO_INITDB_ROOT_PASSWORD
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: repairdb-rs-root-scram
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "500m"
                  memory: "1Gi"
                requests:
                  cpu: "250m"
                  memory: "512Mi"
              lifecycle:
                postStart:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - |
                        if [ -z "$(mongosh --quiet --eval 'rs.status().ok')" ]; then
                          mongosh --eval 'rs.initiate({ _id: "rs0", members: [{ _id: 0, host: "'$HOSTNAME'.repairdb-rs-svc.roadride.svc.cluster.local:27017" }] })'
                        fi
              volumeMounts:
                - name: mongodbdata
                  mountPath: /data/db
      volumeClaimTemplates:
        - metadata:
            name: mongodbdata
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
            storageClassName: standard
