apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: repairdb-rs
  namespace: roadride
spec:
  version: "8.0.1"
  type: ReplicaSet
  members: 1
  security:
    authentication:
      modes:
        - SCRAM
  users:
    - name: root
      db: admin
      passwordSecretRef:
        name: mongodb-admin-secret
        key: MONGO_INITDB_ROOT_PASSWORD
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: repairdb-rs-root-scram
  # For older operator: Enable PVC with size/class (defaults to 8Gi if omitted; operator creates mongodbdata PVC)
  persistent: true
  persistence:
    storage: 2Gi
    storageClass: standard  # Matches Minikube
