architecture: replicaset  # Top-level for replicaset
auth:
  enabled: true
  rootPassword: password  # Change this to something secure!
replica:
  replicaCount: 1  # Single member (primary only)
  replicaSetName: rs0
  arbiter:
    enabled: false  # Disable arbiter (unneeded for 1-member; avoids resources warning)
persistence:
  enabled: true
  size: 2Gi
  storageClass: standard
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
# External access configuration (for NodePort in Minikube)
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true  # Auto-configures replica set with external IPs/ports
  service:
    type: NodePort  # Use NodePort for Minikube (LoadBalancer also works with tunnel)
    nodePorts:      # Optional: Fix ports (27017 for main, 27018 for repl)
      - 30017       # External port for mongodb-mongodb service
      - 30018       # External port for mongodb-mongodb-headless (repl set)
# RBAC and ServiceAccount for auto-discovery
rbac:
  create: true
automountServiceAccountToken: true
