architecture: standalone  # Changed from replicaset
auth:
  enabled: true
  rootPassword: password
persistence:
  enabled: true
  size: 2Gi
  storageClass: standard
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
  service:
    type: NodePort
    # For standalone, nodePorts is a single-entry array
    nodePorts:
      - 27017  # Host port 27017
