apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
  namespace: roadride
  labels:
    app: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo-app
          image: fadedreams7/mongo-app:3
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
