apiVersion: apps/v1
kind: Deployment
metadata:
  name: repair-service
  labels:
    app: repair-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repair-service
  template:
    metadata:
      labels:
        app: repair-service
    spec:
      containers:
      - name: repair-service
        image: repair-service:latest
        imagePullPolicy: Never  # important for minikube local images
        ports:
        - containerPort: 8087   # HTTP port
        - containerPort: 50051 # gRPC port (optional, but good to expose)
        env:
        - name: CONSUL_ADDRESS
          value: "consul:8500"
        - name: JAEGER_ENDPOINT
          value: "http://jaeger:4318/v1/traces"
        - name: SERVICE_PORT
          value: "8087"
        volumeMounts:
        - name: logs
          mountPath: /var/log/repair-service
      volumes:
      - name: logs
        emptyDir: {}
