apiVersion: v1
kind: Service
metadata:
  name: repair-service
spec:
  type: NodePort
  selector:
    app: repair-service
  ports:
    - name: http
      port: 8087
      targetPort: 8087
      nodePort: 30087   # you can change if 30087 is taken
    - name: grpc
      port: 50051
      targetPort: 50051
      nodePort: 30088   # optional – only needed if something calls gRPC directly
