# kafka-values.yaml
auth:
  clientProtocol: sasl
  interBrokerProtocol: sasl
  sasl:
    mechanism: PLAIN
    jaas:
      users:
        - username: user1
          password: password1
        - username: admin
          password: adminpassword
persistence:
  size: 8Gi
resources:
  requests:
    memory: 512Mi
    cpu: 250m
controller:
  replicaCount: 1
broker:
  replicaCount: 0
zookeeper:
  enabled: false
kraft:
  enabled: true
