kafka:
  bootstrapServers: "kafka.roadride.svc.cluster.local:9092"
  securityProtocol: SASL_PLAINTEXT
  saslMechanism: PLAIN  # Change from SCRAM-SHA-256
persistence:
  size: 8Gi
resources:
  requests:
    memory: 256Mi
    cpu: 100m
replicaCount: 1
