apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: api-gateway-logs
  name: api-gateway-logs
  namespace: roadride
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
