apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --out k8s-manifests/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
  namespace: roadride
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml --out k8s-manifests/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: app-config
          image: api-gateway
          name: api-gateway
          ports:
            - containerPort: 8085
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - mountPath: /var/log/api-gateway
              name: api-gateway-logs
      restartPolicy: Always
      volumes:
        - name: api-gateway-logs
          persistentVolumeClaim:
            claimName: api-gateway-logs
