apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-replica
  namespace: roadride
spec:
  members: 1
  type: ReplicaSet
  version: "7.0.12"  # Stable version
  security:
    authentication:
      modes: []  # No authentication
  additionalMongodConfig:
    replSetName: rs0
  statefulSet:
    spec:
      template:
        spec:
          containers:
          - name: mongodb
            volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      volumes:
      - name: init-scripts
        configMap:
          name: mongodb-init
